[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
interfaces = { path = "../interfaces" }
plugin_api = { path = "../plugin/plugin_api" }
plugin_manager = { path = "../plugin/plugin_manager" }
utils = { path = "../utils" }


